### ISSUE TITLE
DataModel.sort() fails if column data is not already loaded.

### ISSUE THREAD

**Issue by xinaesthete** [Taylor-CCB-Group/MDV#51]
Using `ytrap` data on local devserver. When I sort an `ImageTableChart` by certain columns, it throws an error, as a result of the `dataStore` `this.columnIndex[column]` not having a `data` property. If I color-by the same column name before attempting to sort-by it, then it does work.

Currently, I am finding that `"Nerve: Is protein distribution cell-type specific?"` reliably fails in this way.

**Comment by xinaesthete** [comment]
Perhaps I shouldn't be using `getRawColumn()` here, but some other method that will do any necessary data-loading as a side-effect... or perhaps that method should itself have the capacity to allow such side-effects to occur; I'm not sure what the intended design is.

**Comment by martinSergeant** [comment]
Sorry
Any chart methods using columns which are not specified in params needs to flagged  in the the BaseChart types parameter
methodsUsingColumns
The actual method signature requires a string or array specifying the column(s) as the first argument and then any number (or no) other arguments. The method is then decorated to ensure data is loaded before it is run

Similarly any config parameter that refers to a  column should also be in configEntriesUsingColumns in the BaseChart types

As an example , If you look in Image table you will see that the setImageLabel method is flagged for this purpose. 

I will document this now

**Comment by xinaesthete** [comment]
Thanks for the quick response. Adding "sortBy" to `methodsUsingColumns` seems to do the trick (and I added the corresponding config parameter as well).
